kind: pipeline
name: check-app-compatbility

steps:
  - name: check-app-compatbility
    image: nextcloudci/php7.2:php7.2-9
    environment:
      APP_NAME: user_external
      CORE_BRANCH: master
      DB: sqlite
    commands:
      # Pre-setup steps
      - wget https://raw.githubusercontent.com/nextcloud/travis_ci/master/before_install.sh
      - bash ./before_install.sh $APP_NAME $CORE_BRANCH $DB
      - cd ../server

      # Code checker
      - ./occ app:check-code $APP_NAME -c strong-comparison
      - ./occ app:check-code $APP_NAME -c deprecation

matrix:
trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

